### ISSUE TITLE
Dump command hangs when using -c

### ISSUE THREAD

**Issue by davidread** [ckan/ckanapi#103]
I can dump ok using `-r localhost:5000` but not `-c ckan.ini` - it just hangs after printing the first response to the console. ckanapi is waiting for output on stdout but nothing comes, because it is ending up on stderr because that is where `sys.stdout` is pointing:

(Pdb) print sys.stdout
<open file '<stderr>', mode 'w' at 0x7f7a69dd4270>

due to this in dump.py:

        # hack so that "print debugging" can work in extension/ckan
        # code called by this worker
        sys.stdout = sys.stderr

```(ckan)co@precise64:/src/ckan$ ckanapi dump datasets statistics_on_obesity_physical_activity_and_diet_england -c $CKAN_INI
/home/co/ckan/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py:585: SAWarning: Unicode type received non-unicodebind param value.
  processors[key](compiled_params[key])
2016-12-07 08:41:19,553 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
2016-12-07 08:41:19,561 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
2016-12-07 08:41:19,573 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
2016-12-07 08:41:19,577 DEBUG [ckanext.harvest.model] Harvest tables already exist
/home/co/ckan/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py:585: SAWarning: Unicode type received non-unicodebind param value.
  processors[key](compiled_params[key])
2016-12-07 08:41:27,289 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
2016-12-07 08:41:27,293 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
2016-12-07 08:41:27,309 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
2016-12-07 08:41:27,313 DEBUG [ckanext.harvest.model] Harvest tables already exist
["2016-12-07T08:41:27.913396",null,{"license_title":"UK Open Government Licence (OGL)","maintainer":null,"groups":[],"temporal_coverage-
...
e2a63c182527","resource_type":"file"}],"update_frequency":"","revision_id":"000ef760-c074-41f1-94ab-8ceb7e33f3ac","date_released":"25/2/2009","foi-phone":"","sla":"","theme-primary":"Health"}]
^CTraceback (most recent call last):
  File "/home/co/ckan/bin/ckanapi", line 11, in <module>
    load_entry_point('ckanapi', 'console_scripts', 'ckanapi')()
  File "/src/ckanapi/ckanapi/cli/main.py", line 94, in main
    return _switch_to_paster(arguments)
  File "/src/ckanapi/ckanapi/cli/main.py", line 141, in _switch_to_paster
    sys.exit(load_entry_point('PasteScript', 'console_scripts', 'paster')())
  File "/home/co/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/home/co/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/home/co/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/src/ckanapi/ckanapi/cli/paster.py", line 29, in command
    return main.main(running_with_paster=True)
  File "/src/ckanapi/ckanapi/cli/main.py", line 128, in main
    return dump_things(ckan, thing[0], arguments)
  File "/src/ckanapi/ckanapi/cli/dump.py", line 39, in dump_things
    return dump_things_worker(ckan, thing, arguments)
  File "/src/ckanapi/ckanapi/cli/dump.py", line 164, in dump_things_worker
    for line in iter(stdin.readline, b''):
KeyboardInterrupt
```

**Comment by davidread** [comment]
BTW this issue only occurs on CKAN 2.2 with lots of extensions. I don't have a problem on a clean CKAN 2.6.
