### ISSUE TITLE
Error uploading file

### ISSUE THREAD

**Issue by ncarboni** [ckan/ckanapi#16]
Hi, I was just trying ckanapi, and if I can create a dataset without problems, I get instead an error uploading a file (CKAN 2.2a). This is the script that I am using (pretty much the one in the readme): 

    import ckanapi

    mysite = ckanapi.RemoteCKAN('http://url',
        apikey='personalapikey',
        user_agent='test')
    mysite.action.resource_create(
        package_id='dataset_prova',
        description='prova', 
        upload=open('/Users/Nicola/Downloads/Contatti.csv'))

This is the error

    Traceback (most recent call last):
    File "upload.py", line 9, in <module>
    upload=open('/Users/Nicola/Downloads/Contatti.csv'))
    File "/Users/Nicola/anaconda/lib/python2.7/site-packages/ckanapi/common.py", line 49,    in action
    files=files)
    File "/Users/Nicola/anaconda/lib/python2.7/site-packages/ckanapi/remoteckan.py", line 74, in call_action
    return reverse_apicontroller_action(url, status, response)
    File "/Users/Nicola/anaconda/lib/python2.7/site-packages/ckanapi/common.py", line 106, in reverse_apicontroller_action
    raise CKANAPIError(url, status, response)
    TypeError: __init__() takes at most 2 arguments (4 given)

Am I missing something?

**Comment by wardi** [comment]
Sounds like the dataset was not found. are you sure it exists?

**Comment by wardi** [comment]
closing for now. At a minimum this seems like a different problem. If it's still not working let me know and I will reopen
