### ISSUE TITLE
Cannot run on Python 3.10

### ISSUE THREAD

**Issue by frafra** [ckan/ckanapi#191]
```
Traceback (most recent call last):
  File "/home/user/Code/coat-tools/__pypackages__/3.10/bin/ckanapi", line 5, in <module>
    from ckanapi.cli.main import main
  File "/home/user/Code/coat-tools/__pypackages__/3.10/lib/ckanapi/__init__.py", line 19, in <module>
    from ckanapi.remoteckan import RemoteCKAN
  File "/home/user/Code/coat-tools/__pypackages__/3.10/lib/ckanapi/remoteckan.py", line 11, in <module>
    from ckanapi.version import __version__
  File "/home/user/Code/coat-tools/__pypackages__/3.10/lib/ckanapi/version.py", line 1, in <module>
    import pkg_resources
  File "/home/user/Code/coat-tools/__pypackages__/3.10/lib/pkg_resources/__init__.py", line 74, in <module>
    __import__('pkg_resources.extern.packaging.requirements')
  File "/home/user/Code/coat-tools/__pypackages__/3.10/lib/pkg_resources/_vendor/packaging/requirements.py", line 9, in <module>
    from pkg_resources.extern.pyparsing import stringStart, stringEnd, originalTextFor, ParseException
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/home/user/Code/coat-tools/__pypackages__/3.10/lib/pkg_resources/extern/__init__.py", line 43, in load_module
    __import__(extant)
  File "/home/user/Code/coat-tools/__pypackages__/3.10/lib/pkg_resources/_vendor/pyparsing.py", line 943, in <module>
    collections.MutableMapping.register(ParseResults)
AttributeError: module 'collections' has no attribute 'MutableMapping'
```

**Comment by frafra** [comment]
It seems a problem related to an old version of setuptools.
