### ISSUE TITLE
LocalCKAN seems to be broken

### ISSUE THREAD

**Issue by seanh** [ckan/ckanapi#24]
```
Traceback (most recent call last):
  File "3500_unclassified_metadata.py", line 8, in <module>
    ckan = ckanapi.LocalCKAN()
  File "/home/vagrant/projects/ckan/ckanapi/ckanapi/localckan.py", line
 19, in __init__
    username = self.get_site_username()
  File "/home/vagrant/projects/ckan/ckanapi/ckanapi/localckan.py", line
 25, in get_site_username
    user = self._get_action('get_site_user')({'ignore_auth': True}, ())
  File "/home/vagrant/projects/ckan/ckan/ckan/logic/__init__.py", line 
419, in wrapped
    result = _action(context, data_dict, **kw)
  File "/home/vagrant/projects/ckan/ckan/ckan/logic/action/get.py", lin
e 1962, in get_site_user
    user = model.User.get(site_id)
  File "/home/vagrant/projects/ckan/ckan/ckan/model/user.py", line 61, 
in get
    return query.first()
  File "/home/vagrant/.virtualenvs/ckan/local/lib/python2.7/site-packag
es/sqlalchemy/orm/query.py", line 2156, in first
    ret = list(self[0:1])
  File "/home/vagrant/.virtualenvs/ckan/local/lib/python2.7/site-packag
es/sqlalchemy/orm/query.py", line 2023, in __getitem__
    return list(res)
  File "/home/vagrant/.virtualenvs/ckan/local/lib/python2.7/site-packag
es/sqlalchemy/orm/query.py", line 2227, in __iter__
    return self._execute_and_instances(context)
  File "/home/vagrant/.virtualenvs/ckan/local/lib/python2.7/site-packag
es/sqlalchemy/orm/query.py", line 2240, in _execute_and_instances
    close_with_result=True)
  File "/home/vagrant/.virtualenvs/ckan/local/lib/python2.7/site-packag
es/sqlalchemy/orm/query.py", line 2231, in _connection_from_session
    **kw)
  File "/home/vagrant/.virtualenvs/ckan/local/lib/python2.7/site-packag
es/sqlalchemy/orm/session.py", line 727, in connection
    bind = self.get_bind(mapper, clause=clause, **kw)
  File "/home/vagrant/.virtualenvs/ckan/local/lib/python2.7/site-packag
es/sqlalchemy/orm/session.py", line 975, in get_bind
    ', '.join(context)))
sqlalchemy.exc.UnboundExecutionError: Could not locate a bind configure
d on mapper Mapper|User|user, SQL expression or this Session
```

Same traceback on CKAN 2.2, 2.2.1 and master.

This is probably CKAN's fault not ckanapis.

**Comment by metaodi** [comment]
I'm getting the exact same error. Is there an easy fix for it? Btw: if I provide a username it just crashes on the next call (`package_show` in my case).

**Comment by metaodi** [comment]
I found the solution, don't forget to call `self._load_config()` in the paster command, this ensures, that everything is setup correctly, see here: https://github.com/ckan/ckanapi/blob/341c5a56e9f40f6c3a58fe00a108423de569879c/ckanapi/cli/paster.py#L27
