### ISSUE TITLE
Validation/missing value error on `ckanapi dump datasets` (on data.noaa.gov)

### ISSUE THREAD

**Issue by marks** [ckan/ckanapi#43]
`ckanapi` usage and error below. @wardi on IRC suggested I open this issue

Thank you in advance!

```
$ ckanapi dump datasets -r http://data.noaa.gov --all -O json.json
	Traceback (most recent call last):
	  File "/usr/local/bin/ckanapi", line 9, in <module>
	    load_entry_point('ckanapi==3.3', 'console_scripts', 'ckanapi')()
	  File "/Library/Python/2.7/site-packages/ckanapi/cli/main.py", line 95, in main
	    return dump_things(ckan, thing[0], arguments)
	  File "/Library/Python/2.7/site-packages/ckanapi/cli/dump.py", line 33, in dump_things
	    return dump_things_worker(ckan, thing, arguments)
	  File "/Library/Python/2.7/site-packages/ckanapi/cli/dump.py", line 135, in dump_things_worker
	    'include_datasets': False})
	  File "/Library/Python/2.7/site-packages/ckanapi/remoteckan.py", line 82, in call_action
	    return reverse_apicontroller_action(url, status, response)
	  File "/Library/Python/2.7/site-packages/ckanapi/common.py", line 103, in reverse_apicontroller_action
	    raise ValidationError(err)
	ckanapi.errors.ValidationError: {u'__type': u'Validation Error', u'name_or_id': u'Missing value'}
```

**Comment by wardi** [comment]
For some reason post data is being stripped in API calls to data.noaa.gov. You can force ckanapi to use GET requests by adding the `-g` parameter, which seems to work for me.

**Comment by marks** [comment]
Thank you very much, @wardi!
