### ISSUE TITLE
SSL error when dumping

### ISSUE THREAD

**Issue by Noktec** [ckan/ckanapi#51]
There seem to be an error when dumping CKAN catalogues that uses SSL

```
/usr/local/lib/python2.7/dist-packages/requests-2.7.0-py2.7.egg/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/usr/local/bin/ckanapi", line 9, in <module>
    load_entry_point('ckanapi==3.6-dev', 'console_scripts', 'ckanapi')()
  File "/usr/local/lib/python2.7/dist-packages/ckanapi-3.6_dev-py2.7.egg/ckanapi/cli/main.py", line 105, in main
    return dump_things(ckan, thing[0], arguments)
  File "/usr/local/lib/python2.7/dist-packages/ckanapi-3.6_dev-py2.7.egg/ckanapi/cli/dump.py", line 58, in dump_things
    names = ckan.call_action(get_thing_list, {})
  File "/usr/local/lib/python2.7/dist-packages/ckanapi-3.6_dev-py2.7.egg/ckanapi/remoteckan.py", line 80, in call_action
    status, response = self._request_fn_get(url, data_dict, headers, requests_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ckanapi-3.6_dev-py2.7.egg/ckanapi/remoteckan.py", line 90, in _request_fn_get
    r = requests.get(url, params=data_dict, headers=headers, **requests_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.7.0-py2.7.egg/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.7.0-py2.7.egg/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.7.0-py2.7.egg/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

**Comment by wardi** [comment]
Would you try connecting to the site using the requests module and see if you have the same error?
If you do let me know if any of the solutions marked here help:
http://stackoverflow.com/questions/10667960/python-requests-throwing-up-sslerror

I could add a parameter to dump/load etc to disable host verification or provide custom certs.

**Comment by Noktec** [comment]
I actually did that in the code myself, so I do not verify the certificate to enable the download.

**Comment by wardi** [comment]
You can pass requests arguments like `verify=False` if you use call_action https://github.com/ckan/ckanapi/blob/master/ckanapi/remoteckan.py#L53 with `requests_kwargs={'verify': False}`

Closing for now, if you would like to improve that (maybe allow creating of default requests_kwargs) a PR is certainly welcome.
