### ISSUE TITLE
SSLError: hostname 'datahub.io' doesn't match either of '*.ckan.io', 'ckan.io'

### ISSUE THREAD

**Issue by DragosChirila** [ckan/ckanapi#73]
Hi,

I try to connect to https://datahub.io/ using the ckanapi Python Module. My code is this:

import ckanapi

ckan = ckanapi.RemoteCKAN('http://datahub.io/api',
    apikey = 'my_api_key_here',
    user_agent='ckanapiexample/1.0 (+http://example.com/my/website)')

packages = ckan.action.package_list()
print packages

I get the following error:
Traceback (most recent call last):
  File "test-ckanapi.py", line 7, in <module>
    packages = ckan.action.package_list()
  File "C:\Program Files (x86)\Python27\lib\site-packages\ckanapi-3.6_dev-py2.7.egg\ckanapi\common.py", line 51, in action
    return self._ckan.call_action(name, data_dict=kwargs)
  File "C:\Program Files (x86)\Python27\lib\site-packages\ckanapi-3.6_dev-py2.7.egg\ckanapi\remoteckan.py", line 82, in call_action
    status, response = self._request_fn(url, data, headers, files, requests_kwargs)
  File "C:\Program Files (x86)\Python27\lib\site-packages\ckanapi-3.6_dev-py2.7.egg\ckanapi\remoteckan.py", line 86, in _request_fn
    r = requests.post(url, data=data, headers=headers, files=files, **requests_kwargs)
  File "C:\Program Files (x86)\Python27\lib\site-packages\requests-2.2.0-py2.7.egg\requests\api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "C:\Program Files (x86)\Python27\lib\site-packages\requests-2.2.0-py2.7.egg\requests\api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Program Files (x86)\Python27\lib\site-packages\requests-2.2.0-py2.7.egg\requests\sessions.py", line 383, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files (x86)\Python27\lib\site-packages\requests-2.2.0-py2.7.egg\requests\sessions.py", line 506, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Program Files (x86)\Python27\lib\site-packages\requests-2.2.0-py2.7.egg\requests\sessions.py", line 168, in resolve_redirects
    allow_redirects=False,
  File "C:\Program Files (x86)\Python27\lib\site-packages\requests-2.2.0-py2.7.egg\requests\sessions.py", line 486, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files (x86)\Python27\lib\site-packages\requests-2.2.0-py2.7.egg\requests\adapters.py", line 389, in send
    raise SSLError(e)
requests.exceptions.SSLError: hostname 'datahub.io' doesn't match either of '*.ckan.io', 'ckan.io'

Am I doing something wrong?

**Comment by DragosChirila** [comment]
nevermind, I moved to http://demo.ckan.org and it works fine.

**Comment by rossjones** [comment]
You may have just caught datahub.io at a bad time as it was transferring to another machine.  Would it be possible to try this again now so we can close the issue?  Thanks.

**Comment by DragosChirila** [comment]
Still, not working. https://datahub.io/ was of course online at that moment as I was working on it.

Thanks.

**Comment by wardi** [comment]
This seems like a server/SSL issue unrelated to ckanapi, please let me know if I'm wrong about that.

**Comment by DragosChirila** [comment]
querying datahub.io using the deprecated client https://github.com/okfn/ckanclient-deprecated works, here is code:

import ckanclient

ckan = ckanclient.CkanClient(base_location='http://datahub.io/api',
    api_key='my_api_key_here')

packages = ckan.package_register_get()
print packages

**Comment by wardi** [comment]
@DragosChirila your working example isn't using https. Try ckanapi without https and it will work too

**Comment by DragosChirila** [comment]
I don't understand. From my first post:

import ckanapi

ckan = ckanapi.RemoteCKAN('http://datahub.io/api',
apikey = 'my_api_key_here',
user_agent='ckanapiexample/1.0 (+http://example.com/my/website)')

packages = ckan.action.package_list()
print packages

What do you mean by "Try ckanapi without https and it will work too"? Thanks

**Comment by wardi** [comment]
Oh, I'm sorry. What's happening is that ckanapi is using POST requests and it looks like POST requests are being redirected on datahub.io (which is terrible, and they should stop doing that).

You can use RemoteCKAN(..., get_only=True) to force ckanapi to only use get requests. You won't be able to update any data though. I suspect that would be broken in CkanClient too, unless it's handling redirects very differently than ckanapi is.

**Comment by DragosChirila** [comment]
Yes, I see now. Thank you very much for your time and answer :)
