### ISSUE TITLE
python3 issue

### ISSUE THREAD

**Issue by fccoelho** [ckan/ckanapi#95]
I got this error while trying to run  the following  command from the readme:

```
ckanapi action group_list -r http://dados.gov.br
```

``` python
Traceback (most recent call last):
  File "/usr/local/bin/ckanapi", line 11, in <module>
    load_entry_point('ckanapi==3.6', 'console_scripts', 'ckanapi')()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2621, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2281, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2287, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/ckanapi/cli/main.py", line 112
    except CLIError, e:
                   ^
SyntaxError: invalid syntax

```

the except clause has not been made compatible with python 3.x syntax

**Comment by wardi** [comment]
@fccoelho good catch! Care to submit a PR?

**Comment by zbyte64** [comment]
Don't forget to handle encoding:

```
Traceback (most recent call last):
  File "/Users/jasonkraus/anaconda/bin/ckanapi", line 11, in <module>
    sys.exit(main())
  File "/Users/jasonkraus/anaconda/lib/python3.5/site-packages/ckanapi/cli/main.py", line 110, in main
    sys.stdout.write(r)
TypeError: write() argument must be str, not bytes
```

**Comment by zbyte64** [comment]
My question is this: why are the tests passing for python 3?

**Comment by wardi** [comment]
The python 3 tests cover use of ckanapi as a library. For the CLI I assumed it would run under python 2 (thinking it shouldn't matter to people just running a command), but if you don't have python 2 then you'll have a problem.

**Comment by wardi** [comment]
One problem with running the ckanapi CLI under python 3 is that it won't work for local CKAN commands (commands run on the same server without using HTTP) because CKAN itself doesn't run on Python 3 yet.

**Comment by fccoelho** [comment]
Sure,  I'll make a PR soon. fixing these two things.

**Comment by rwillmer** [comment]
The PR submitted by @fccoelho has fixes for this and one other problem. https://github.com/ckan/ckanapi/pull/96

The other solution to the other problem started some discussion which has stalled so the PR hasn't AFAICS been accepted yet.

Could we either (a) conclude that discussion, or (b) have a PR for a fix for this specific bug? I'll submit one if that's useful

**Comment by wardi** [comment]
@rwillmer thanks for the reminder, I've replied on #96

**Comment by varunmaitreya** [comment]
hello,
i faced similar kind of issue even with python2.7 as well. I am a newbie to python and need some help understanding ckanapi
```
varun@varun-X756UXK:~$ sudo -H pip install ckanapi
Collecting ckanapi
Requirement already satisfied: docopt in /usr/lib/python2.7/dist-packages (from ckanapi) (0.6.2)
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages (from ckanapi) (2.18.4)
Requirement already satisfied: simplejson in /usr/local/lib/python2.7/dist-packages (from ckanapi) (3.15.0)
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages (from ckanapi) (39.0.1)
Installing collected packages: ckanapi
Successfully installed ckanapi-4.1
varun@varun-X756UXK:~$ sudo ckanapi action group_list -r http://demo.ckan.org
Traceback (most recent call last):
  File "/usr/local/bin/ckanapi", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/ckanapi/cli/main.py", line 110, in main
    for r in action(ckan, arguments):
  File "/usr/local/lib/python2.7/dist-packages/ckanapi/cli/action.py", line 53, in action
    files=file_args)
  File "/usr/local/lib/python2.7/dist-packages/ckanapi/remoteckan.py", line 87, in call_action
    return reverse_apicontroller_action(url, status, response)
  File "/usr/local/lib/python2.7/dist-packages/ckanapi/common.py", line 131, in reverse_apicontroller_action
    raise CKANAPIError(repr([url, status, response]))
ckanapi.errors.CKANAPIError: ['http://demo.ckan.org/api/action/group_list', 302, u'Found']
```
did i do anything wrong anywhere?

**Comment by TkTech** [comment]
@varunmaitreya this is an unrelated error. Use `http*s*://demo.ckan.org`

**Comment by varunmaitreya** [comment]
@TkTech thank you :+1: now it works. It's a pity that i did miss that small thing.
